### ISSUE TITLE
Some assembly instructions in mips32r2 are not decoded in dasm view

### ISSUE THREAD

**Issue by richardhilbig** [mips-open-ide/Releases#16]
toolchain: 2018.09-03 mips-mti-elf 
mips-mti-elf-gcc -msoft-float -mips32r2 -mabi=32 -EL -Tuhi32.ld -o "simple-mips-mti-elf.elf" $(OBJS) $(USER_OBJS) $(LIBS)

same program as in video, stepping through the return:
The proper instructions are shown in the quotes:
802018f8:   move t0,zero
802018fc:   move t1,zero
80201900:   0x400a8003 		"mfc0      t2, Config3"
80201904:   0x7d4b06c0 		"ext       t3, t2, 0x1b, 0x1"
80201908:   beqz t3,0x80201914 <_mips_xtlb_refill+196>
8020190c:   nop 
80201910:   0x40084002 		"mfc0      t0, BadInstrP"
80201914:   0x7d4a0680 		"ext       t2, t2, 0x1a, 0x1"
80201918:   beqz t2,0x80201924 <_mips_xtlb_refill+212>

80201818:   lw t9,96(t0)
8020181c:   0x7000007f 		"sdbbp"

The last instruction is what causes the debugger to be unable to halt the core. Since the core will not halt, the debug session cannot be terminated; I must exit the IDE manually and then kill qemu.

**Comment by kurt-wave** [comment]
I would like to add my own notes on this issue.  Richard is describing the same termination sequence that I explained in issue #14 .  In this sequence, you can see that the 0x7000007f opcode cannot be decoded as SDBBP by the disassembler.  That is the bug that is being reported here.  The fact that the execution of the SDBBP at the end of the program causes the session to be unable to be terminated is a separate bug, and that bug is the topic of issue #14 .

There are other opcodes beyond SDBBP that are not recognized by the disassembler.  Here are more examples:
![image](https://user-images.githubusercontent.com/48976304/55184833-5eba1e00-5150-11e9-9416-8aef7d09fb3f.png)

I think we need to fix the disassembler to be able to recognize these opcodes.

Kurt

**Comment by tuanha-viosoft** [comment]
@richardhilbig @kurt-wave Thanks. We are resolving it.

**Comment by tuanha-viosoft** [comment]
It was fixed in the release v1.0.20190402.
