### ISSUE TITLE
Is file I/O (semihosting) supported?  Also, how do you pass args to a program?

### ISSUE THREAD

**Issue by kurt-wave** [mips-open-ide/Releases#25]
Hi,

I installed the 1.0.0.201905070348 version of the IDE on Windows.  I can now see the output from printf in the console window.  Thanks for adding that support.

Is file I/O also supported?  I tried running a simple bare-metal program that reads a file and then writes to a new file.  But the fopen() command is not able to open the file.

I put the file that I'm trying to open in the same directory as the program.  I have attached the program, Makefile, and input data file.

I also am not able to figure out how to pass arguments to the program being debugged.  Is there somewhere I can do this?  I even tried the "set args" command from the gdb command window in the debugger.

Kurt

[mergesort.zip](https://github.com/mips-open-ide/Releases/files/3167928/mergesort.zip)

**Comment by tuanha-viosoft** [comment]
Hi Kurt,

> Is file I/O also supported? I tried running a simple bare-metal program that reads a file and then writes to a new file. But the fopen() command is not able to open the file.

The I/O is supported. I checked your code, please use the absolute path instead of relative path and it works.
![image](https://user-images.githubusercontent.com/17974406/57568177-f7a9ad80-740d-11e9-9834-87910f9411cc.png)

![image](https://user-images.githubusercontent.com/17974406/57568190-11e38b80-740e-11e9-828d-eddb77aeab2e.png)


> I also am not able to figure out how to pass arguments to the program being debugged. Is there somewhere I can do this? I even tried the "set args" command from the gdb command window in the debugger.

On both Run and Debug configuration, the IDE always creates a Run configuration to interact with I/O. You can pass the arguments to the program by changing the arguments of Run configuration. Currently, we are setting the default arguments "foo, bar", you can edit it.
![image](https://user-images.githubusercontent.com/17974406/57568247-c7aeda00-740e-11e9-8499-f28ea53e93b8.png)

![image](https://user-images.githubusercontent.com/17974406/57568257-f7f67880-740e-11e9-96cb-89f6df4f0615.png)

![image](https://user-images.githubusercontent.com/17974406/57568278-3429d900-740f-11e9-881b-bff949730841.png)

**Comment by kurt-wave** [comment]
Hi Tuanha,

Thanks, that totally answered my question.  I really appreciate the clear and easy to understand response.  I'm very happy with this semihosting support!  I will close this issue now.
